In [1]:
import torchinfo, torchmetrics, torch

# Check for GPU (should return True)
print(torch.cuda.is_available())

True


In [2]:
!nvidia-smi -L

GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU (UUID: GPU-98579472-7258-af99-7b4b-bbcd2dce65c8)


In [3]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib

# Introduction to Tensors

Creating tensors

In [4]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

6

In [7]:
# Vector
vector = torch.tensor([6,6])
vector

tensor([6, 6])

In [8]:
vector.shape, vector.ndim

(torch.Size([2]), 1)

In [9]:
# Matrix 
MATRIX = torch.tensor([[1, 6],
                      [9, 6]])

MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[1, 6],
         [9, 6]]),
 2,
 torch.Size([2, 2]))

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

# Random Tensors

In [12]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0189, 0.8977, 0.1606, 0.6496],
        [0.2633, 0.4820, 0.3726, 0.2774],
        [0.2533, 0.5345, 0.2017, 0.0145]])

In [13]:
random_tensor.shape, random_tensor.ndim

(torch.Size([3, 4]), 2)

In [14]:
# create a random tensor with similar shape as image
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [15]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [16]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, zeros.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# creating a range and tensors like

In [17]:
# use torch.arange()
# zero_to_ten_deprecated = torch.range(0, 10)

# create a range of values 0 to 10
zero_to_ten = torch.arange(0, 11, 1)
zero_to_ten, zero_to_ten.dtype

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.int64)

In [18]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [19]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.4, 6.0, 7.2],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [20]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor_half = torch.tensor([3.2, 6.0, 8.8],
                                   dtype=torch.half)  # torch.float16 and torch.half are same

float_16_tensor, float_16_tensor_half

(tensor([3., 6., 9.], dtype=torch.float16),
 tensor([3.1992, 6.0000, 8.7969], dtype=torch.float16))

## Getting information from tensors

In [21]:
# Create a tensor
some_tensor = torch.rand(4, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2062, 0.8272, 0.4940, 0.8640],
        [0.5154, 0.1305, 0.6938, 0.0389],
        [0.2378, 0.4990, 0.9607, 0.3726],
        [0.4434, 0.2968, 0.6237, 0.1120]])
Shape of tensor: torch.Size([4, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating Tensors (tensor operations)

In [22]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [23]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [24]:
tensor - 11

tensor([-1,  9, 19])

In [25]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [26]:
torch.matmul(tensor, torch.tensor([[1,2,3],
                                  [2,3,4],
                                  [3,4,5]]))

tensor([140, 200, 260])

In [27]:
torch.tensor([[1,2,3],[2,3,4],[3,4,5]]).shape

torch.Size([3, 3])