In [7]:
import torchinfo, torchmetrics

# Check for GPU (should return True)
print(torch.cuda.is_available())

True


In [8]:
!nvidia-smi -L

GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU (UUID: GPU-98579472-7258-af99-7b4b-bbcd2dce65c8)


In [ ]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib

# Introduction to Tensors

Creating tensors

In [9]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [10]:
scalar.ndim

0

In [12]:
scalar.item()

6

In [14]:
# Vector
vector = torch.tensor([6,6])
vector

tensor([6, 6])

In [16]:
vector.shape, vector.ndim

(torch.Size([2]), 1)

In [19]:
# Matrix 
MATRIX = torch.tensor([[1, 6],
                      [9, 6]])

MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[1, 6],
         [9, 6]]),
 2,
 torch.Size([2, 2]))

In [21]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

# Random Tensors

In [28]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2743, 0.9963, 0.0236, 0.1777],
        [0.1403, 0.2404, 0.4803, 0.8427],
        [0.4271, 0.7267, 0.6366, 0.2301]])

In [30]:
random_tensor.shape, random_tensor.ndim

(torch.Size([3, 4]), 2)

In [33]:
# create a random tensor with similar shape as image
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [38]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [37]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, zeros.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# creating a range and tensors like

In [42]:
# use torch.arange()
# zero_to_ten_deprecated = torch.range(0, 10)

# create a range of values 0 to 10
zero_to_ten = torch.arange(0, 11, 1)
zero_to_ten, zero_to_ten.dtype

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.int64)

In [43]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [51]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.4, 6.0, 7.2],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [55]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor_half = torch.tensor([3.2, 6.0, 8.8],
                                   dtype=torch.half)  # torch.float16 and torch.half are same

float_16_tensor, float_16_tensor_half

(tensor([3., 6., 9.], dtype=torch.float16),
 tensor([3.1992, 6.0000, 8.7969], dtype=torch.float16))

## Getting information from tensors

In [57]:
# Create a tensor
some_tensor = torch.rand(4, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3275, 0.2026, 0.9332, 0.9032],
        [0.7579, 0.2276, 0.9700, 0.1266],
        [0.0953, 0.4454, 0.5391, 0.0462],
        [0.3995, 0.7233, 0.5607, 0.2225]])
Shape of tensor: torch.Size([4, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
